### ISSUE TITLE
Assets composition/genericity

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#15756]
```[tasklist]
### Tasks
- [ ] https://github.com/glpi-project/glpi/pull/15729
- [x] Support templates feature (not deactivable)
- [x] Support clone feature (not deactivable)
- [x] Support models/types definition (not deactivable)
- [x] Support transfer (not deactivable)
- [x] Allow configuration of status visibility for each asset definition
- [x] Add ability to translate definition name (including plural forms)
- [x] Create a reusable icon selector for asset definiton icon field and icon search option
- [ ] Allow plugins to add capacities
- [x] ~Optimize handling of logs related to a disabled capacity (real time deletion request may be too long)~
- [ ] Allow to change System name, via a dedicated form/action, and store history to handle API deprecations
- [x] Add asset rights configuration in profile form
- [x] Warn user about data loss when capacities are disabled
- [x] ~Make log deletion asynchronous when a capacity is disabled (move deletion in log cleaner cron)~
- [ ] Add ability to define new menu sections (assets families)
- [x] Properly handle definition deletion (ask for confirmation and clean assets)
- [ ] Add ability to move an asset into another definition
- [ ] Find a way to handle saved searches related to a disabled capacity
```

**Comment by cedric-anne** [comment]
I guess we can close this one. Remaining tasks are listed in the backlog.
